name: Create Release (Reusable)

on:
  workflow_call:
    inputs:
      version:
        required: false
        type: string
      changelog_path:
        required: true
        type: string

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create Release
        run: |
          VERSION=${{ inputs.version }}
          if [ -z "$VERSION" ]; then
            VERSION="v$(date +'%Y.%m.%d')"
          fi
          echo "Creating release $VERSION"
          gh release create "$VERSION" -F "${{ inputs.changelog_path }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
