name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (optional)'
        required: false

jobs:
  call-create-release:
    uses: your-org/.github/.github/workflows/create-release.yml@main
    with:
      changelog_path: CHANGELOG.md
      version: ${{ github.event.inputs.version }}