name: Create Release from Changelog

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 1.0.0)'
        required: false
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  check-changelog:
    runs-on: ubuntu-latest
    outputs:
      should_release: ${{ steps.check.outputs.should_release }}
      version: ${{ steps.extract.outputs.version }}
      release_notes: ${{ steps.extract.outputs.release_notes }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Check if changelog has unreleased version
        id: check
        run: |
          if [ -f "CHANGELOG.md" ]; then
            # Check for [Unreleased] section with content
            if grep -A 5 "## \[Unreleased\]" CHANGELOG.md | grep -q "^- \|^### "; then
              echo "should_release=true" >> $GITHUB_OUTPUT
              echo "✅ Found unreleased changes in CHANGELOG.md"
            else
              echo "should_release=false" >> $GITHUB_OUTPUT
              echo "ℹ️ No unreleased changes found in CHANGELOG.md"
            fi
          else
            echo "should_release=false" >> $GITHUB_OUTPUT
            echo "⚠️ CHANGELOG.md not found"
          fi
      
      - name: Extract version and release notes
        id: extract
        if: steps.check.outputs.should_release == 'true' || github.event.inputs.version != ''
        run: |
          # Determine version
          if [ -n "${{ github.event.inputs.version }}" ]; then
            VERSION="${{ github.event.inputs.version }}"
          else
            # Get latest version from CHANGELOG or git tags
            LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
            LATEST_VERSION=${LATEST_TAG#v}
            
            # Parse semantic version
            IFS='.' read -ra VERSION_PARTS <<< "$LATEST_VERSION"
            MAJOR=${VERSION_PARTS[0]:-0}
            MINOR=${VERSION_PARTS[1]:-0}
            PATCH=${VERSION_PARTS[2]:-0}
            
            # Increment patch version by default
            PATCH=$((PATCH + 1))
            VERSION="$MAJOR.$MINOR.$PATCH"
          fi
          
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "📦 Version: $VERSION"
          
          # Extract unreleased section from CHANGELOG
          RELEASE_NOTES=$(awk '/## \[Unreleased\]/{flag=1; next} /## \[.*\]/{flag=0} flag' CHANGELOG.md | sed '/^$/d')
          
          # Save to file for multiline output
          echo "$RELEASE_NOTES" > /tmp/release_notes.txt
          
          # Create multiline output
          {
            echo 'release_notes<<EOF'
            cat /tmp/release_notes.txt
            echo EOF
          } >> $GITHUB_OUTPUT
          
          echo "📝 Release notes extracted"

  create-release:
    needs: check-changelog
    if: needs.check-changelog.outputs.should_release == 'true' || github.event.inputs.version != ''
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      
      - name: Update CHANGELOG.md
        run: |
          VERSION="${{ needs.check-changelog.outputs.version }}"
          TODAY=$(date +%Y-%m-%d)
          
          # Replace [Unreleased] with [Version] - Date
          sed -i "s/## \[Unreleased\]/## [Unreleased]\n\n## [$VERSION] - $TODAY/" CHANGELOG.md
          
          echo "✅ Updated CHANGELOG.md with version $VERSION"
      
      - name: Commit changelog update
        run: |
          VERSION="${{ needs.check-changelog.outputs.version }}"
          git add CHANGELOG.md
          
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Release version $VERSION"
            git push origin ${{ github.ref_name }}
            echo "✅ Committed and pushed changelog update"
          fi
      
      - name: Create git tag
        run: |
          VERSION="${{ needs.check-changelog.outputs.version }}"
          git tag -a "v$VERSION" -m "Release version $VERSION"
          git push origin "v$VERSION"
          echo "✅ Created and pushed tag v$VERSION"
      
      - name: Create GitHub Release
        uses: actions/github-script@v7
        with:
          script: |
            const version = '${{ needs.check-changelog.outputs.version }}';
            const releaseNotes = `${{ needs.check-changelog.outputs.release_notes }}`;
            
            const { data: release } = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: `v${version}`,
              name: `Release ${version}`,
              body: releaseNotes || 'No release notes provided.',
              draft: false,
              prerelease: false
            });
            
            console.log(`✅ Created release: ${release.html_url}`);
            core.summary.addHeading(`Release ${version} Created! 🎉`);
            core.summary.addLink('View Release', release.html_url);
            core.summary.write();

  no-release:
    needs: check-changelog
    if: needs.check-changelog.outputs.should_release == 'false' && github.event.inputs.version == ''
    runs-on: ubuntu-latest
    
    steps:
      - name: No release needed
        run: |
          echo "ℹ️ No unreleased changes found. Skipping release creation."
          echo "To create a release manually, trigger this workflow with a version input."
